FROM docker.io/gplane/pnpm as buildstage
COPY ./package.json /build/
WORKDIR /build
RUN pnpm install
COPY ./ /build
RUN pnpm run build
# RUN
FROM docker.io/node:20-alpine

# Create non-root user
RUN addgroup -g 10001 -S appgroup && \
    adduser -u 10001 -S appuser -G appgroup

COPY --from=buildstage --chown=appuser:appgroup /build/.output/ /app
WORKDIR /app

USER appuser
EXPOSE 3000
ENTRYPOINT ["node", "server/index.mjs"]