api:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-api
  replicas: 1
  type: ClusterIP
  walletApi2:
    image:
      repository: waltid/wallet-api2
      tag: latest
      imagePullPolicy: Always

pvc:
  dataVolumeClaim:
    accessMode: ReadWriteOnce
    storageClass: gp3-retain
    storageRequest: 1Gi

ingress:
  ingressClassName: "traefik"
  host: wallet-api2.portal.waltid.cloud