package id.walt.issuer2.testsupport

import id.walt.crypto.utils.JwsUtils.decodeJws
import id.walt.issuer2.domain.IssuanceSession
import id.waltid.openid4vci.wallet.token.TokenRequestBuilder
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.client.statement.bodyAsText
import io.ktor.http.HttpStatusCode
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.time.Instant

fun assertBearerAccessToken(tokenResponse: TokenRequestBuilder.TokenResponse) {
    assertTrue(tokenResponse.token_type.equals("bearer", ignoreCase = true))
    assertTrue(tokenResponse.access_token.isNotBlank())
}

suspend fun assertSessionStatus(
    client: HttpClient,
    sessionId: String,
    expectedStatus: String,
) {
    val response = client.get("/issuer2/sessions/$sessionId")
    assertEquals(HttpStatusCode.OK, response.status, response.bodyAsText())

    // ACTIVE is the default enum value and is omitted from JSON when encodeDefaults=false.
    // Decode the session so Kotlin serialization applies the same default the service uses.
    val session = response.body<IssuanceSession>()
    assertEquals(expectedStatus, session.status.name)
}

fun assertJwtVcJsonCredentialPayload(credentialPayload: JsonObject): String {
    val issuedCredential = assertNotNull(
    val issuedCredential = issuedCredentialString(credentialPayload)
    assertTrue(issuedCredential.split(".").size >= 3)
    assertJwtVcJsonMappingFunctionsApplied(issuedCredential)
    return issuedCredential
}

fun assertSdJwtVcCredentialPayload(
    credentialPayload: JsonObject,
    expectedVctSuffix: String,
    expectedDisclosureKeys: Set<String>,
): String {
    val issuedCredential = issuedCredentialString(credentialPayload)
    assertTrue(issuedCredential.endsWith("~"), "Expected SD-JWT VC to end with the disclosure separator")

    val sdJwt = SDJwt.parse(issuedCredential)
    assertEquals("dc+sd-jwt", sdJwt.type)
    assertSdJwtVcDisclosures(sdJwt, expectedDisclosureKeys)
    assertTrue(
        assertStringClaim(sdJwt.fullPayload["vct"], "sd-jwt.vct").endsWith(expectedVctSuffix),
        "Expected SD-JWT VC vct to end with $expectedVctSuffix",
    )
    return issuedCredential
}

private fun assertSdJwtVcDisclosures(
    sdJwt: SDJwt,
    expectedDisclosureKeys: Set<String>,
) {
    val disclosures = sdJwt.disclosureObjects

    assertTrue(disclosures.isNotEmpty(), "Expected SD-JWT VC to include at least one parsed disclosure")
    assertEquals(disclosures.size, sdJwt.disclosures.size)
    assertEquals(expectedDisclosureKeys, disclosures.map { it.key }.toSet())
    assertTrue(sdJwt.sdPayload.verifyDisclosures(), "Expected SD-JWT VC disclosures to match the payload digests")
    disclosures.forEachIndexed { index, disclosure ->
        assertTrue(disclosure.salt.isNotBlank(), "Expected SD-JWT VC disclosure #$index to have a salt")
        assertTrue(disclosure.key.isNotBlank(), "Expected SD-JWT VC disclosure #$index to have a claim key")
    }
}

private fun issuedCredentialString(credentialPayload: JsonObject): String =
    assertNotNull(
        credentialPayload["credentials"]
            ?.jsonArray
            ?.single()
            ?.jsonObject
            ?.get("credential")
            ?.jsonPrimitive
            ?.content
    )
    assertTrue(issuedCredential.split(".").size >= 3)
    assertJwtVcJsonMappingFunctionsApplied(issuedCredential)
    return issuedCredential
}

private fun assertJwtVcJsonMappingFunctionsApplied(issuedCredential: String) {
    val jwtPayload = issuedCredential.decodeJws().payload
    val vc = jwtPayload["vc"]?.jsonObject ?: jwtPayload
    val credentialSubject = assertNotNull(vc["credentialSubject"]?.jsonObject)

    // UniversityDegree is the default W3C wallet-flow profile. Its profile mapping uses
    // <uuid>, <issuerDid>, <subjectDid>, and <timestamp>; the issued JWT must contain
    // resolved values, not the config placeholders.
    val vcText = vc.toString()
    assertFalse(vcText.contains("THIS WILL BE REPLACED WITH DYNAMIC DATA FUNCTION"))
    assertFalse(vcText.contains("<uuid>"))
    assertFalse(vcText.contains("<issuerDid>"))
    assertFalse(vcText.contains("<subjectDid>"))
    assertFalse(vcText.contains("<timestamp>"))

    assertTrue(
        assertStringClaim(vc["id"], "vc.id").startsWith("urn:uuid:"),
        "Expected vc.id to be generated by <uuid>",
    )
    assertTrue(
        assertStringClaim(vc["issuer"]?.jsonObject?.get("id"), "vc.issuer.id").startsWith("did:jwk:"),
        "Expected vc.issuer.id to be resolved from <issuerDid>",
    )
    assertTrue(
        assertStringClaim(credentialSubject["id"], "vc.credentialSubject.id").startsWith("did:jwk:"),
        "Expected vc.credentialSubject.id to be resolved from <subjectDid>",
    )
    Instant.parse(assertStringClaim(vc["issuanceDate"], "vc.issuanceDate"))
}

private fun assertStringClaim(value: JsonElement?, claimName: String): String =
    assertNotNull(value?.jsonPrimitive?.contentOrNull, "Expected $claimName")