package id.walt.walletdemo.compose.ui

internal object WalletUiTestTags {
    val Status = tag("status")
    val CredentialsEmpty = tag("credentials", "empty")
    val WalletHome = tag("home")
    val HomeReceiveButton = tag("home", "receive")
    val HomePresentButton = tag("home", "present")
    val RequestCaptureSheet = tag("requestCaptureSheet")
    val RequestManualInput = tag("requestManualInput")
    val CredentialDetailsScreen = tag("credentialDetailsScreen")
    val DetailsBack = tag("detailsBack")
    val Did = tag("did")
    val OfferInput = tag("offerInput")
    val OfferScanButton = tag("offerScanButton")
    val TxCodeInput = tag("txCodeInput")
    val ReceiveButton = tag("receiveButton")
    val ReceiveNewButton = tag("receiveNewButton")
    val ReceiveTabContent = tag("receiveTabContent")
    val OfferReview = tag("offerReview")
    val OfferIssuerSection = tag("offerIssuerSection")
    val OfferCredentialsSection = tag("offerCredentialsSection")
    val OfferSupportedClaims = tag("offerSupportedClaims")
    val OfferTransactionCodeSection = tag("offerTransactionCodeSection")
    val OfferAcceptButton = tag("offerAcceptButton")
    val OfferDeclineButton = tag("offerDeclineButton")
    val PresentationInput = tag("presentationInput")
    val PresentationScanButton = tag("presentationScanButton")
    val PresentButton = tag("presentButton")
    val PresentationNewButton = tag("presentationNewButton")
    val PresentTabContent = tag("presentTabContent")
    val PresentationReview = tag("presentationReview")
    val PresentationError = tag("presentationError")
    val PresentationErrorNotifyButton = tag("presentationErrorNotifyButton")
    val PresentationErrorDismissButton = tag("presentationErrorDismissButton")
    val PresentationActions = tag("presentationActions")
    val PresentationSubmitButton = tag("presentationSubmitButton")
    val PresentationRejectButton = tag("presentationRejectButton")
    val PresentationCancelButton = tag("presentationCancelButton")
    val PresentationVerifier = tag("presentationVerifier")
    val PresentationVerifierSection = tag("presentationVerifierSection")
    val PresentationResponseProtectionSection = tag("presentationResponseProtectionSection")
    val PresentationTechnicalDetailsSection = tag("presentationTechnicalDetailsSection")
    val VerifierTechnicalDetailsToggle = tag("verifierTechnicalDetailsToggle")
    val VerifierTechnicalDetails = tag("verifierTechnicalDetails")
    val PinInput = tag("pinInput")
    val PinConfirmationInput = tag("pinConfirmationInput")
    val PinSubmitButton = tag("pinSubmitButton")
    val CredentialsTab = tag("tab", "credentials")
    val ReceiveTab = tag("tab", "receive")
    val PresentTab = tag("tab", "present")

    fun claim(path: String): String = dynamicTag("claim", path)
    fun claimImage(path: String): String = dynamicTag("claimImage", path)
    fun claimGroup(title: String): String = dynamicTag("claimGroup", title)
    fun credentialCard(id: String): String = tag("credentialCard", id)
    fun credentialDetails(id: String): String = tag("credentialDetails", id)
    fun credentialOverview(id: String): String = tag("credentialOverview", id)
    fun presentationCredential(id: String): String = tag("presentationCredential", id)
    fun presentationCredentialToggle(id: String): String = tag("presentationCredentialToggle", id)
    fun presentationDisclosure(id: String): String = tag("presentationDisclosure", id)
    fun presentationDisclosureToggle(id: String): String = tag("presentationDisclosureToggle", id)

    private fun tag(vararg segments: String): String =
        (listOf(Namespace) + segments).joinToString(separator = ".")

    private fun dynamicTag(kind: String, rawValue: String): String =
        tag(kind, rawValue.toTestTagSegment())

    private const val Namespace = "wallet"
}

private fun String.toTestTagSegment(): String =
    map { if (it.isLetterOrDigit()) it else '_' }.joinToString("")
