package id.walt.walletdemo.compose.ui

internal object WalletUiTestTags {
    val Status = tag("status")
    val StatusDismiss = tag("statusDismiss")
    val StatusExpand = tag("statusExpand")
    val CredentialsEmpty = tag("credentials", "empty")
    val CredentialDetailsScreen = tag("credentialDetailsScreen")
    val DetailsBack = tag("detailsBack")
    val DetailsMenu = tag("detailsMenu")
    val CopyRawCredential = tag("copyRawCredential")
    val DeleteCredential = tag("deleteCredential")
    val DeleteCredentialConfirm = tag("deleteCredentialConfirm")
    val AppTitle = tag("appTitle")
    val SettingsButton = tag("settingsButton")
    val SettingsScreen = tag("settingsScreen")
    val SettingsBack = tag("settingsBack")
    val SettingsDid = tag("settingsDid")
    val SettingsDidCopy = tag("settingsDidCopy")
    val SettingsKeyId = tag("settingsKeyId")
    val SettingsKeyIdCopy = tag("settingsKeyIdCopy")
    val SettingsPublicJwk = tag("settingsPublicJwk")
    val SettingsPublicJwkCopy = tag("settingsPublicJwkCopy")
    val SettingsCredentialSharing = tag("settingsCredentialSharing")
    val SettingsShowDcApiPreview = tag("settingsShowDcApiPreview")
    val SettingsLock = tag("settingsLock")
    val SettingsReset = tag("settingsReset")
    val SettingsResetConfirm = tag("settingsResetConfirm")
    val SigningProtectionBiometric = tag("signingProtectionBiometric")
    val SigningProtectionNone = tag("signingProtectionNone")
    val SigningProtectionConfirm = tag("signingProtectionConfirm")
    val SigningProtectionRetry = tag("signingProtectionRetry")
    val SigningProtectionError = tag("signingProtectionError")
    val SigningProtectionAvailability = tag("signingProtectionAvailability")
    val SigningProtectionWarning = tag("signingProtectionWarning")
    val SigningProtectionWarningDismiss = tag("signingProtectionWarningDismiss")
    val Did = tag("did")
    val OfferInput = tag("offerInput")
    val OfferScanButton = tag("offerScanButton")
    val TxCodeInput = tag("txCodeInput")
    val ReceiveButton = tag("receiveButton")
    val ReceiveNewButton = tag("receiveNewButton")
    val ReceiveTabContent = tag("receiveTabContent")
    val OfferReview = tag("offerReview")
    val OfferIssuerSection = tag("offerIssuerSection")
    val OfferIssuerDetailsToggle = tag("offerIssuerDetailsToggle")
    val OfferIssuerDetails = tag("offerIssuerDetails")
    val OfferCredentialsSection = tag("offerCredentialsSection")
    val OfferSupportedClaims = tag("offerSupportedClaims")
    val OfferAuthorizationSection = tag("offerAuthorizationSection")
    val OfferTransactionCodeSection = tag("offerTransactionCodeSection")
    val OfferAcceptButton = tag("offerAcceptButton")
    val OfferDeclineButton = tag("offerDeclineButton")
    val PresentationInput = tag("presentationInput")
    val PresentationScanButton = tag("presentationScanButton")
    val PresentButton = tag("presentButton")
    val ProximityStartButton = tag("proximityStartButton")
    val ProximityScreen = tag("proximityScreen")
    val ProximityStatus = tag("proximityStatus")
    val ProximityQr = tag("proximityQRCode")
    val ProximityReview = tag("proximityReview")
    val ProximityContinueAfterResponse = tag("proximityContinueAfterResponse")
    val ProximityApprove = tag("proximityApproveButton")
    val ProximityDecline = tag("proximityDeclineButton")
    val ProximityCancel = tag("proximityCancelButton")
    val ProximityDone = tag("proximityDoneButton")
    val ProximityRetry = tag("proximityRetryButton")
    val ProximityError = tag("proximityError")
    fun proximityCredential(requestIndex: Int, credentialId: String): String =
        tag("proximityCredential", requestIndex.toString(), credentialId.toTestTagSegment())
    fun proximityElement(requestIndex: Int, namespace: String, elementIdentifier: String): String =
        tag(
            "proximityElement",
            requestIndex.toString(),
            "$namespace.$elementIdentifier".toTestTagSegment(),
        )
    val PresentationNewButton = tag("presentationNewButton")
    val PresentTabContent = tag("presentTabContent")
    val PresentationReview = tag("presentationReview")
    val PresentationError = tag("presentationError")
    val PresentationErrorNotifyButton = tag("presentationErrorNotifyButton")
    val PresentationErrorDismissButton = tag("presentationErrorDismissButton")
    val PresentationActions = tag("presentationActions")
    val PresentationSubmitButton = tag("presentationSubmitButton")
    val PresentationRejectButton = tag("presentationRejectButton")
    val PresentationCancelButton = tag("presentationCancelButton")
    val PresentationVerifier = tag("presentationVerifier")
    val PresentationVerifierSection = tag("presentationVerifierSection")
    val PresentationClaimsDialog = tag("presentationClaimsDialog")
    val PresentationClaimsClose = tag("presentationClaimsClose")
    val PresentationRequesterDetailsToggle = tag("presentationRequesterDetailsToggle")
    val PresentationRequesterDetails = tag("presentationRequesterDetails")
    val PresentationReaderTrustSection = tag("presentationReaderTrustSection")
    val PresentationResponseProtectionSection = tag("presentationResponseProtectionSection")
    val PresentationTechnicalDetailsSection = tag("presentationTechnicalDetailsSection")
    val VerifierTechnicalDetailsToggle = tag("verifierTechnicalDetailsToggle")
    val VerifierTechnicalDetails = tag("verifierTechnicalDetails")
    val PinInput = tag("pinInput")
    val PinScreen = tag("pinScreen")
    val PinConfirmationInput = tag("pinConfirmationInput")
    val PinSubmitButton = tag("pinSubmitButton")
    val PinBiometricToggle = tag("pinBiometricToggle")
    val PinBiometricButton = tag("pinBiometricButton")
    val CredentialsTab = tag("tab", "credentials")
    val ReceiveTab = tag("tab", "receive")
    val PresentTab = tag("tab", "present")

    fun claim(path: String): String = dynamicTag("claim", path)
    fun claimImage(path: String): String = dynamicTag("claimImage", path)
    fun claimGroup(title: String): String = dynamicTag("claimGroup", title)
    val CredentialCardConstructedArt = tag("credentialCardConstructedArt")
    fun credentialCard(id: String): String = tag("credentialCard", id)
    fun credentialDetails(id: String): String = tag("credentialDetails", id)
    fun credentialOverview(id: String): String = tag("credentialOverview", id)
    fun presentationCredential(id: String): String = tag("presentationCredential", id)
    fun presentationCredentialToggle(id: String): String = tag("presentationCredentialToggle", id)
    fun presentationClaimsToggle(id: String): String = tag("presentationClaimsToggle", id)
    fun presentationDisclosure(id: String): String = tag("presentationDisclosure", id)
    fun presentationDisclosureToggle(id: String): String = tag("presentationDisclosureToggle", id)

    private fun tag(vararg segments: String): String =
        (listOf(Namespace) + segments).joinToString(separator = ".")

    private fun dynamicTag(kind: String, rawValue: String): String =
        tag(kind, rawValue.toTestTagSegment())

    private const val Namespace = "wallet"
}

private fun String.toTestTagSegment(): String =
    map { if (it.isLetterOrDigit()) it else '_' }.joinToString("")
