api:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-api
  replicas: 1
  type: ClusterIP
  issuerApi2:
    image:
      repository: waltid/issuer-api2
      tag: latest
      imagePullPolicy: Always

configFiles:
  _features.conf: |-
    enabledFeatures = [
        entra
    ]
  issuer-service.conf: |-
    baseUrl = "https://{{ .Values.ingress.host }}"

ingress:
  ingressClassName: traefik # nginx
  host: issuer2.portal.waltid.cloud