# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'shared', :path => '../shared/build/cocoapods/publish/debug/shared.podspec'

end
