{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.fullname" . }}-data-volume-claim
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageRequest | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
