"""Generate public certificate/CRL vectors for the native Swift bridge tests.

Uses Python cryptography/OpenSSL independently of the SDK. Keys exist only in
memory. The long 2020-2099 interval isolates bridge behavior from wall-clock
expiry; production freshness boundaries are exercised in the shared tests.
"""
from base64 import b64encode
from datetime import datetime, timezone
from pathlib import Path
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import NameOID

key = ec.generate_private_key(ec.SECP256R1())
reader_key = ec.generate_private_key(ec.SECP256R1())
issuer = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "Swift CRL bridge test CA")])
start = datetime(2020, 1, 1, tzinfo=timezone.utc)
end = datetime(2099, 1, 1, tzinfo=timezone.utc)
ski = x509.SubjectKeyIdentifier.from_public_key(key.public_key())
aki = x509.AuthorityKeyIdentifier.from_issuer_subject_key_identifier(ski)
points = x509.CRLDistributionPoints([x509.DistributionPoint(
    [x509.UniformResourceIdentifier("https://crl.example.test/swift.crl")], None, None, None)])


def certificate(ca):
    return (x509.CertificateBuilder().subject_name(issuer if ca else x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, "Swift CRL bridge reader")]))
        .issuer_name(issuer).public_key((key if ca else reader_key).public_key())
        .serial_number(1 if ca else 2).not_valid_before(start).not_valid_after(end)
        .add_extension(x509.BasicConstraints(ca, 0 if ca else None), True)
        .add_extension(x509.KeyUsage(not ca, False, False, False, False, ca, ca, None, None), True)
        .add_extension(ski if ca else x509.SubjectKeyIdentifier.from_public_key(reader_key.public_key()), False)
        .add_extension(aki, False).add_extension(points, False).sign(key, hashes.SHA256()))


def crl(serial=None):
    builder = (x509.CertificateRevocationListBuilder().issuer_name(issuer).last_update(start).next_update(end)
               .add_extension(aki, False).add_extension(x509.CRLNumber(1), False))
    if serial is not None:
        builder = builder.add_revoked_certificate(x509.RevokedCertificateBuilder()
            .serial_number(serial).revocation_date(start)
            .add_extension(x509.CRLReason(x509.ReasonFlags.key_compromise), False).build())
    return builder.sign(key, hashes.SHA256())


vectors = {"issuer": certificate(True), "reader": certificate(False),
           "good": crl(), "readerRevoked": crl(2), "authorityRevoked": crl(1)}
root = next(parent for parent in Path(__file__).resolve().parents if (parent / "settings.gradle.kts").is_file())
out = root / "waltid-applications/waltid-wallet-demo-ios/iosApp/iosAppTests/ProximityCRLFixtures.swift"
lines = ["// Generated by waltid-wallet-sdk-ios/scripts/generate-crl-swift-fixtures.py.",
         "// Public material only. The 2020-2099 interval isolates Swift bridge behavior from expiry.",
         "import Foundation", "", "enum ProximityCRLFixtures {"]
for name, value in vectors.items():
    encoded = b64encode(value.public_bytes(serialization.Encoding.DER)).decode()
    lines += [f"    static let {name} = Data(base64Encoded:", f'        "{encoded}"', "    )!"]
lines += ["}", ""]
out.write_text("\n".join(lines))
print(f"Wrote {len(vectors)} public Swift bridge vectors to {out}")
