server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;

    types {
        application/wasm wasm;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/wasm application/json;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
