CREATE DATABASE $(MSSQL_DB_NAME);
GO
USE $(MSSQL_DB_NAME);

IF NOT EXISTS (SELECT * FROM sys.sql_logins WHERE name = '$(MSSQL_DB_USR)')
BEGIN
    CREATE LOGIN [$(MSSQL_DB_USR)] WITH PASSWORD = '$(MSSQL_DB_PWD)', CHECK_POLICY = OFF;
    ALTER SERVER ROLE [sysadmin] ADD MEMBER [$(MSSQL_DB_USR)];
END
GO