apiVersion: apps/v1
kind: Deployment
metadata:
  name: podman-priv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podman-priv
  template:
    metadata:
      labels:
        app: podman-priv
    spec:
      containers:
        - name: podman
          image: mgoltzsche/podman:4.9.5-minimal
          securityContext:
            privileged: true
          command: ["sh", "-c", "
          echo 'http://dl-cdn.alpinelinux.org/alpine/edge/main' > /etc/apk/repositories && \
          echo 'http://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories && \
          echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
          cat /etc/apk/repositories && \
          apk update && \
          apk upgrade && \
          apk add --no-cache podman-compose git py3-pip && \
          adduser -D waltid && \
          git clone https://github.com/walt-id/waltid-identity.git && \
          chown -R waltid:waltid /waltid-identity && \
          cd /waltid-identity/docker-compose && \
          chmod -R a+rw wallet-api/data && \
          podman compose pull && \
          podman compose up "]