apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-service.fullname" . }}-service
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.type }}
  selector:
    app: {{ include "api-service.name" . }}
    {{- include "api-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-api
