apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.fullname" . }}-web-config
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.configFiles }}
  {{ $name }}: |
    {{- tpl $content $ | nindent 4 }}
  {{- end }}
