apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "verifier2.fullname" . }}
  labels:
    {{- include "verifier2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: verifier2
    {{- include "verifier2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: verifier2
      {{- include "verifier2.labels" . | nindent 8 }}
      annotations:
        deployment/id: _DEFAULT_DEPLOYMENT_
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: verifier2
        image: {{ .Values.api.verifierApi2.image.repository }}:{{ .Values.api.verifierApi2.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.verifierApi2.image.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
          - name: http-api
            containerPort: 7003
        volumeMounts:
        {{- range $name, $content := .Values.configFiles }}
        - mountPath: /waltid-verifier-api2/config/{{ $name }}
          name: verifier2-web-config
          subPath: {{ $name }}
          readOnly: true
        {{- end }}
      volumes:
      - configMap:
          name: {{ include "verifier2.fullname" . }}-web-config
        name: verifier2-web-config
