import id.walt.crypto.keys.jwk.JWKKey
import kotlin.test.Test

class ConversionTests {

    companion object {

        private const val MIME_ENCODED_PEM_CERTIFICATE = """
-----BEGIN CERTIFICATE-----
MIIC8TCCApigAwIBAgIKXkW8UsGZRHyHyDAKBggqhkjOPQQDAjB1MQswCQYDVQQG
EwJBVTEtMCsGA1UEAwwkQXVzdHJvYWRzIFByZS1wcm9kdWN0aW9uIERUUyBSb290
IENBMTcwNQYDVQQKDC5BdXN0cm9hZHMgUHJlLXByb2R1Y3Rpb24gRGlnaXRhbCBU
cnVzdCBTZXJ2aWNlMB4XDTI0MDkwMjAzMjQ0MVoXDTQ0MDkwMjAzMjQ0MVowdTEL
MAkGA1UEBhMCQVUxLTArBgNVBAMMJEF1c3Ryb2FkcyBQcmUtcHJvZHVjdGlvbiBE
VFMgUm9vdCBDQTE3MDUGA1UECgwuQXVzdHJvYWRzIFByZS1wcm9kdWN0aW9uIERp
Z2l0YWwgVHJ1c3QgU2VydmljZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMJt
zT2r7UHttv6jSGEso6dVKF9QwsEyXcb4EUzciXonsLIorpUiG5tuuIUoD0fRbGNV
KD4yA3KJs6R8pe/94c6jggEOMIIBCjASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1Ud
DwEB/wQEAwIBBjAdBgNVHQ4EFgQUjQCqUhB6NiazWEI4a0qWZ7mXlRYwgcQGA1Ud
HwSBvDCBuTCBtqCBs6CBsIaBrWh0dHBzOi8vYXVzdHJvYWRzLWR0cy1wcmUtcHJk
LnZpaS5hdTAxLm1hdHRyLmdsb2JhbC92MS9lY29zeXN0ZW1zLzljOTVmNjY2LWNk
Y2UtNGU4YS1iY2Q3LWRkNzQ0ZjQ3ODhmNC92aWNhbHMvcHVibGljL2NlcnRpZmlj
YXRlcy9jYS9kOTRkZTEyNi1lOTgyLTRmOTUtYTUzNS1iZDA3NjcwOWU2NmYvY3Js
MAoGCCqGSM49BAMCA0cAMEQCIGxwNRWAq0B4DU/OlHjal0gULknk3JD4w1+Mtrpb
yPxFAiAaQMxnrcRJopU6SRrNTq1x29UlFJdaE7XHvdXu1sXnDA==
-----END CERTIFICATE-----
        """
    }

    @Test
    fun testConversionWithMimeEncodedPemCertificate() {
        JWKKey.convertDERorPEMtoByteArray(MIME_ENCODED_PEM_CERTIFICATE)
    }
}