@file:OptIn(kotlin.io.encoding.ExperimentalEncodingApi::class)

package id.walt.walletdemo.compose.ui

import kotlin.io.encoding.Base64

/**
 * Signed ICAO Doc 9303 Part 13 v4 residence-permit test seal generated by
 * https://sealgen.tsenger.de/ with signer certificate reference UTTS5B.
 *
 * SHA-256: 82c99a4eb83713c55f508f86645e753bb38c3d7d9751c7aebe7dd200b713f575
 * The exact payload was verified with VdsTools, KURZ Code Scan, and Sealva on 2026-09-02.
 */
internal object SignedIcaoVdsFixture {
    const val BYTE_COUNT = 142

    fun bytes(): ByteArray = Base64.Default.decode(BASE64_PAYLOAD)

    private const val BASE64_PAYLOAD =
        "3APZxdnKyKc6mYmqSomqSvsGAjBcuhNYdZduwGbUF7WejGq8EzwTPBM8Ezw/7zopOO5D8Vk9GuUtuyZ1H+ZLfBM8E2sDBteVGaZTBv9AdGJ3k4iqXB2UvvYh0SXUxFsY/4PjUTcJwXIf9IRKuNQ6/3P5dLrOkTKGOY/OOu2WqkosoZV7w/pU+JOznw0lEQ=="
}
