package id.walt.commons.interop

object LspPotentialInterop {
  val POTENTIAL_ROOT_CA_CERT = "-----BEGIN CERTIFICATE-----${System.lineSeparator()}" +
          "MIIBZDCCAQmgAwIBAgII2x50/ui7K2wwCgYIKoZIzj0EAwIwFzEVMBMGA1UEAwwMTURPQyBST09UIENBMB4XDTI1MDUwNTA5NDAxNVoXDTI2MDUwNTA5NDAxNVowFzEVMBMGA1UEAwwMTURPQyBST09UIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWP0sG+CkjItZ9KfM3sLF+rLGb8HYCfnlsIH/NWJjiXkTx57ryDLYfTU6QXYukVKHSq6MEebvQPqTJT1blZ/xeKM/MD0wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMWhsBrivmW3c2DagA08if4Ki0cJMAoGCCqGSM49BAMCA0kAMEYCIQCierJhChwclbWNvUo0uqQRxDlIFHIGIjPuWP/Hq165YgIhALTywPN4vTXm0Z6MGNlvfbwWXdyoZ7D5XmkjvljXJfBt${System.lineSeparator()}" +
          "-----END CERTIFICATE-----${System.lineSeparator()}"
  val POTENTIAL_ISSUER_CERT = "-----BEGIN CERTIFICATE-----${System.lineSeparator()}" +
          "MIIBdjCCAR0CFCgQqkF7ufAOIHtyFwUo4/ia1oJcMAoGCCqGSM49BAMCMBcxFTATBgNVBAMMDE1ET0MgUk9PVCBDQTAeFw0yNTA1MTQxMTA4MTNaFw0yNjA1MTQxMTA4MTNaMGUxCzAJBgNVBAYTAkFUMQ8wDQYDVQQIDAZWaWVubmExDzANBgNVBAcMBlZpZW5uYTEQMA4GA1UECgwHd2FsdC5pZDEQMA4GA1UECwwHd2FsdC5pZDEQMA4GA1UEAwwHd2FsdC5pczBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBtESDQYhfqEFA93eQxp3oELl3pyNvSQ2jBqDL4qCkQTed3eFGs2pEtrp7vAZ7BLcbrUtpKkYWAT2JPUQK4lN4EwCgYIKoZIzj0EAwIDRwAwRAIgHn7x5gEY1dFIvwiXzfw2h0exTbV3H+iFQJRMBXNsgNMCIH3zRKizvcLnoVUGGWLtcXTW5odDfPNq1/38yvNLcrvG${System.lineSeparator()}" +
      "-----END CERTIFICATE-----"
  val POTENTIAL_ISSUER_PUB = "-----BEGIN PUBLIC KEY-----${System.lineSeparator()}" +
          "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEG0RINBiF+oQUD3d5DGnegQuXenI29JDaMGoMvioKRBN53d4UazakS2unu8BnsEtxutS2kqRhYBPYk9RAriU3gQ==${System.lineSeparator()}" +
          "-----END PUBLIC KEY-----${System.lineSeparator()}"
  val POTENTIAL_ISSUER_PRIV = "-----BEGIN PRIVATE KEY-----${System.lineSeparator()}" +
          "MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCAoniTdVyXlKP0x+rius1cGbYyg+hjf8CT88hH8SCwWFA==${System.lineSeparator()}" +
          "-----END PRIVATE KEY-----${System.lineSeparator()}"
  const val POTENTIAL_ISSUER_KEY_ID = "potential-lsp-issuer-key-01"
}
