package id.walt.x509.iso.iaca

import id.walt.x509.iso.IsoSharedTestHarnessValidResources
import kotlinx.coroutines.test.runTest
import kotlin.test.Test

class IACACertificateRoundTripMPTest {

    @Test
    fun `parser should correctly decode IACA certificate generated by builder for all valid keyTypes`() = runTest {
        IsoSharedTestHarnessValidResources
            .iacaSigningKeyMap()
            .values
            .forEach { validIacaKey ->

                val iacaCertBundle = IsoSharedTestHarnessValidResources
                    .iacaBuilder
                    .build(
                    profileData = IsoSharedTestHarnessValidResources.iacaProfileData,
                    signingKey = validIacaKey,
                )
            }
    }
}