package id.walt.x509.iso.iaca

import id.walt.x509.iso.IsoSharedTestHarnessValidResources
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class IACACertificateRoundTripMPTest {

    @Test
    fun `parser should correctly decode IACA certificate generated by builder for all valid keyTypes`() = runTest {
        IsoSharedTestHarnessValidResources
            .iacaSigningKeyMap()
            .values
            .forEach { validIACAKey ->

                val iacaCertBundle = IsoSharedTestHarnessValidResources
                    .iacaBuilder
                    .build(
                        profileData = IsoSharedTestHarnessValidResources.iacaProfileData,
                        signingKey = validIACAKey,
                    )

                val decodedCert = IsoSharedTestHarnessValidResources
                    .iacaParser
                    .parse(
                        certificate = iacaCertBundle.certificateDer,
                    )

                assertEquals(
                    expected = iacaCertBundle.decodedCertificate,
                    actual = decodedCert,
                )

                IsoSharedTestHarnessValidResources.iacaValidator.validate(
                    decodedCert = decodedCert,
                )

            }
    }

    @Test
    fun `roundtrip should be safe when called concurrently`() = runTest {

        val bundles = List(20) {
            async {
                val iacaCertBundle = IsoSharedTestHarnessValidResources.iacaBuilder.build(
                    profileData = IsoSharedTestHarnessValidResources.iacaProfileData,
                    signingKey = IsoSharedTestHarnessValidResources.iacaSecp256r1SigningKey(),
                )

                val decodedCert = IsoSharedTestHarnessValidResources.iacaParser.parse(
                    certificate = iacaCertBundle.certificateDer,
                )

                IsoSharedTestHarnessValidResources.iacaValidator.validate(
                    decodedCert = decodedCert,
                )
                iacaCertBundle
            }
        }.awaitAll()

        assertTrue {
            bundles.all { it.certificateDer.bytes.size != 0 }
        }

        //all serial numbers are unique -> hence all generated certificates different
        assertEquals(
            expected = bundles.size,
            actual = bundles.map { it.decodedCertificate.serialNumber }.toSet().size,
        )
    }
}
