package id.walt.x509.iso.iaca

import id.walt.x509.iso.IsoSharedTestHarnessValidResources
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals

class IACACertificateRoundTripMPTest {

    @Test
    fun `parser should correctly decode IACA certificate generated by builder for all valid keyTypes`() = runTest {
        IsoSharedTestHarnessValidResources
            .iacaSigningKeyMap()
            .values
            .forEach { validIACAKey ->

                val iacaCertBundle = IsoSharedTestHarnessValidResources
                    .iacaBuilder
                    .build(
                        profileData = IsoSharedTestHarnessValidResources.iacaProfileData,
                        signingKey = validIACAKey,
                    )

                val decodedCert = IsoSharedTestHarnessValidResources
                    .iacaParser
                    .parse(
                        certificate = iacaCertBundle.certificateDer,
                    )

                assertEquals(
                    expected = iacaCertBundle.decodedCertificate,
                    actual = decodedCert,
                )

                IsoSharedTestHarnessValidResources.iacaValidator.validate(
                    decodedCert = decodedCert,
                )

            }
    }
}