issuer:
  ingress:
    ingressClassName: "traefik"
    clusterIssuer: letsencrypt-prod
    tls:
      - hosts:
          - issuer.portal.test.waltid.cloud
        secretName: issuer-tls-secret
    host: issuer.portal.test.waltid.cloud

issuer2:
  ingress:
    ingressClassName: "traefik"
    clusterIssuer: letsencrypt-prod
    tls:
      - hosts:
          - issuer2.portal.test.waltid.cloud
        secretName: issuer2-tls-secret
    host: issuer2.portal.test.waltid.cloud

verifier:
  ingress:
    ingressClassName: "traefik"
    clusterIssuer: letsencrypt-prod
    tls:
      - hosts:
          - verifier.portal.test.waltid.cloud
        secretName: verifier-tls-secret
    host: verifier.portal.test.waltid.cloud

verifier2:
  ingress:
    ingressClassName: "traefik"
    clusterIssuer: letsencrypt-prod
    tls:
      - hosts:
          - verifier2.portal.test.waltid.cloud
        secretName: verifier2-tls-secret
    host: verifier2.portal.test.waltid.cloud

portal:
  env:
    NEXT_PUBLIC_VC_REPO: "https://credentials.walt.id"
    NEXT_PUBLIC_ISSUER: "https://issuer.portal.test.waltid.cloud"
    NEXT_PUBLIC_VERIFIER: "https://verifier.portal.test.waltid.cloud"
    NEXT_PUBLIC_WALLET: "https://wallet.test.waltid.cloud"
  ingress:
    ingressClassName: "traefik"
    clusterIssuer: letsencrypt-prod
    tls:
      - hosts:
          - portal.test.waltid.cloud
        secretName: portal-tls-secret
    host: portal.test.waltid.cloud

web-wallet:
  pvc:
    dataVolumeClaim:
      accessMode: ReadWriteOnce
      storageClass: gp3-retain
      storageRequest: 1Gi
  configFiles:
    oidc.conf: |-
      publicBaseUrl = "https://wallet-dev.test.waltid.cloud"
      providerName = keycloak
      oidcRealm = "https://keycloak.walt-test.cloud/realms/waltid-keycloak-ktor"
      oidcJwks = "${oidcRealm}/protocol/openid-connect/certs"
      authorizeUrl = "${oidcRealm}/protocol/openid-connect/auth"
      accessTokenUrl = "${oidcRealm}/protocol/openid-connect/token"
      logoutUrl = "${oidcRealm}/protocol/openid-connect/logout"
      clientId = "wallet_backend_prod"
      clientSecret = "__DEFAULT_KEYCLOAK_CLIENT_SECRET__"
      keycloakUserApi = "https://keycloak.walt-test.cloud/admin/realms/waltid-keycloak-ktor/users"
      jwksCache = {
          cacheSize = 10
          cacheExpirationHours = 24
          rateLimit: {
              bucketSize: 10
              refillRateMinutes: 1
          }
      }
  walletConfig:
    authConf: |-
      encryptionKey = "oshaaddgtwcqvcsg"
      signKey = "gyccmrunkqwnzswl"
      tokenKey = "bsbybnzroezpsttdeerwjiymkqzzlxqz"
      tokenLifetime = "30"
      audTokenClaim = "https://wallet.walt.id"
      issTokenClaim = "https://wallet.walt.id"
  web:
    credentialsRepository:
      host: credentials.walt.id
    devUi:
      host: wallet-dev.test.waltid.cloud
    demoUi:
      host: wallet.test.waltid.cloud
  ingress:
    ingressClassName: "traefik"
    clusterIssuer: letsencrypt-prod
    tls:
      - hosts:
          - wallet-dev.test.waltid.cloud
          - wallet.test.waltid.cloud
        secretName: wallet-tls-secret

wallet-api2:
  ingress:
    ingressClassName: "traefik"
    clusterIssuer: letsencrypt-prod
    tls:
      - hosts:
          - wallet-api2.portal.test.waltid.cloud
        secretName: wallet-api2-tls-secret
    host: wallet-api2.portal.test.waltid.cloud