name = "keycloak"
authorizeUrl = "http://keycloak.localhost:8080/realms/issuer/protocol/openid-connect/auth"
accessTokenUrl = "http://keycloak.localhost:8080/realms/issuer/protocol/openid-connect/token"
clientId = "issuer-api"
clientSecret = "issuer-api-secret"
defaultScopes = ["openid", "profile"]
forwardIssuerStateToAuthorizationServer = true