name = "keycloak"
authorizeUrl = "https://keycloak.demo.walt.id/realms/mynewrealm/protocol/openid-connect/auth"
accessTokenUrl = "https://keycloak.demo.walt.id/realms/mynewrealm/protocol/openid-connect/token"
clientId = "issuer_api"
clientSecret = "Y0DyNhF4NgpOS6VMRUtl0JtvxrRYQD4s"
defaultScopes = ["openid", "profile"]
forwardIssuerStateToAuthorizationServer = false