issuerDisplay = [
  {
    name = "walt.id OSS Issuer2"
    locale = "en"
    description = "Open-source OpenID4VCI issuer"
  }
]

credentialConfigurations = {
  UniversityDegree_jwt_vc_json = {
    format = "jwt_vc_json"
    cryptographic_binding_methods_supported = ["did"]
    credential_signing_alg_values_supported = ["EdDSA", "ES256"]
    credential_definition = {
      type = ["VerifiableCredential", "UniversityDegreeCredential"]
    }
  }
}
