baseUrl = "http://localhost:7004"

# Token signing key for access tokens (JWK format)
tokenKey = {
    type: "jwk"
    jwk: {
        kty: "EC"
        d: "AEb4k1BeTR9xt2NxYZggdzkFLLUkhyyWvyUOq3qSiwA"
        crv: "P-256"
        kid: "issuer-token-key"
        x: "G_TgBc0BkmMipiQ_6gkamIn3mmp7hcTrZuyrLTmknP0"
        y: "VkRMZdXYXSMff5AJLrnHiN0x5MV6u_8vrAcytGUe4z4"
    }
}
