profiles = {
  universityDegree = {
    name = "University Degree"
    credentialConfigurationId = "UniversityDegree_jwt_vc_json"
    issuerKeyId = "default"
    credentialData = {
      type = ["VerifiableCredential", "UniversityDegreeCredential"]
      credentialSubject = {}
    }
    mapping = {
      id = "<uuid>"
      issuer = { id = "<issuerDid>" }
      credentialSubject = { id = "<subjectDid>" }
    }
    idTokenClaimsMapping = {
      "sub" = "$.credentialSubject.id"
      "given_name" = "$.credentialSubject.givenName"
      "family_name" = "$.credentialSubject.familyName"
    }
  }
}
