baseUrl = "http://localhost:7002"

ciTokenKey = """{"type":"jwk","jwk":{"kty":"EC","d":"KJ4k3Vcl5Sj9Mfq4rrNXBm2MoPoY3_Ak_PIR_EgsFhQ","crv":"P-256","x":"G0RINBiF-oQUD3d5DGnegQuXenI29JDaMGoMvioKRBM","y":"ed3eFGs2pEtrp7vAZ7BLcbrUtpKkYWAT2JPUQK4lN4E"}}"""

clientAuthenticationConfig {
  supportedMethods = [
    {
      type = "preauth-anonymous"
    },
    {
      type = "client-attestation"
      config {
        verificationMethod {
          type = "static-jwk"
          jwk {
            kty = "EC"
            crv = "P-256"
            x = "f83OJ3D2xF4mNqA6x0Y6qf9jR9sM8f2Q1gW0m2yPj9k"
            y = "x_FEzRu9k5D4Q0h9sVQXK2fAq8rLz4jN0wQ1Xy2aP5M"
          }
        }
      }
    }
  ]
}
