package id.walt.webdatafetching

enum class WebDataFetcherId {
    DATA_FUNCTIONS,
    WELL_KNOWN_KEY_RESOLVER,
    WEBHOOK_POLICY,
    WEBHOOK_POLICY2,
    OPENID4VP_WALLET_RESOLVE_AUTHORIZATIONREQUEST,
    OPENID4VP_WALLET_POST_TOKEN
}
