package id.walt.x509.iso.documentsigner

import id.walt.x509.iso.IsoSharedTestHarnessValidResources
import id.walt.x509.iso.documentsigner.builder.IACASignerSpecification
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertEquals

class DocumentSignerCertificateRoundTripMPTest {

    @Test
    fun `parser should correctly decode Document signer certificate generated by builder for all valid keyTypes`() =
        runTest {
            IsoSharedTestHarnessValidResources
                .dsKeyMap()
                .values
                .forEach { validDSKey ->

                    val iacaCertBundle = IsoSharedTestHarnessValidResources
                        .iacaBuilder
                        .build(
                            profileData = IsoSharedTestHarnessValidResources.iacaProfileData,
                            signingKey = IsoSharedTestHarnessValidResources.iacaSecp256r1SigningKey(),
                        )

                    val dsCertBundle = IsoSharedTestHarnessValidResources
                        .dsBuilder
                        .build(
                            profileData = IsoSharedTestHarnessValidResources.dsProfileData,
                            publicKey = validDSKey.getPublicKey(),
                            iacaSignerSpec = IACASignerSpecification(
                                profileData = IsoSharedTestHarnessValidResources.iacaProfileData,
                                signingKey = IsoSharedTestHarnessValidResources.iacaSecp256r1SigningKey(),
                            ),
                        )

                    val dsDecodedCert = IsoSharedTestHarnessValidResources
                        .dsParser
                        .parse(
                            certificate = dsCertBundle.certificateDer,
                        )

                    assertEquals(
                        expected = dsCertBundle.decodedCertificate,
                        actual = dsDecodedCert,
                    )

                    IsoSharedTestHarnessValidResources.dsValidator.validate(
                        dsDecodedCert = dsDecodedCert,
                        iacaDecodedCert = iacaCertBundle.decodedCertificate,
                    )

                }
        }
}