enabledFeatures = [
    # dev-mode # Enabling developer config from file `dev-mode.conf`
    # auth # Enable user authentication
    wallet2-persistence # Enable SQL persistence (SQLite/Postgres)
]
disabledFeatures = [
    # ...
]
