enabledFeatures = [
    # dev-mode # Enabling developer config from file `dev-mode.conf`
    auth # Enable user authentication (email/password JWT; see auth.conf)
    wallet2-persistence # Enable SQL persistence (SQLite/Postgres)
]
disabledFeatures = [
    # ...
]
