wallet2-persistence {
    jdbcUrl = "jdbc:postgresql://${POSTGRES_DB_HOST}:5432/${DB_NAME}"
    driverClassName = "org.postgresql.Driver"
    username = "${DB_USERNAME}"
    password = "${DB_PASSWORD}"
    maximumPoolSize = 10
    minimumIdle = 2
}
