name: Deploy manually to branch based environments

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.set_version.outputs.release_version }}
    steps:
      - name: Inject enhanced GitHub environment variables
        uses: rlespinasse/github-slug-action@v5
      - name: Set release version
        id: set_version
        run: echo "release_version=${GITHUB_REF_SLUG}" >> $GITHUB_OUTPUT
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      tags: '["dev", "latest"]'
      publish: true
  api-docker:
    uses: ./.github/workflows/api-docker.yml
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      tags: '["dev", "latest"]'
      publish: true
  deploy:
    uses: ./.github/workflows/helm-deployment.yml
    secrets: inherit
    needs: [ version, docker, api-docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      namespace: ${{ needs.version.outputs.release_version }}
