name: Build and push docker (reusable workflow)

on:
  workflow_call:
    inputs:
      version:
        description: "release version"
        required: true
        type: string
      tag:
        description: "desired tag, e.g. latest, dev (defaults to dev)"
        required: false
        type: string
        default: "dev"
      publish:
        description: "Specifies whether to publish the images (defaults to false)"
        required: false
        type: boolean
        default: false


jobs:
  build:
    name: "Build"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        if: ${{ inputs.publish }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        if: ${{ !inputs.publish }}
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images (issuer)
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.publish }}
          file: waltid-services/waltid-issuer-api/Dockerfile
          tags: waltid/issuer-api:${{ inputs.tag }}, waltid/issuer-api:${{ inputs.version }}
      - name: Build and push Docker images (verifier)
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.publish }}
          file: waltid-services/waltid-verifier-api/Dockerfile
          tags: waltid/verifier-api:${{ inputs.tag }}, waltid/verifier-api:${{ inputs.version }}
      - name: Build and push Docker images (wallet-api)
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.publish }}
          file: waltid-services/waltid-wallet-api/Dockerfile
          tags: waltid/wallet-api:${{ inputs.tag }}, waltid/wallet-api:${{ inputs.version }}
      - name: Build and push Docker images (waltid-demo-wallet)
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.publish }}
          file: waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/Dockerfile
          tags: waltid/waltid-demo-wallet:${{ inputs.tag }}, waltid/waltid-demo-wallet:${{ inputs.version }}
      - name: Build and push Docker images (waltid-dev-wallet)
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.publish }}
          file: waltid-applications/waltid-web-wallet/apps/waltid-dev-wallet/Dockerfile
          tags: waltid/waltid-dev-wallet:${{ inputs.tag }}, waltid/waltid-dev-wallet:${{ inputs.version }}
      - name: Build and push Docker images (wallet-portal)
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.publish }}
          file: waltid-applications/waltid-web-portal/Dockerfile
          tags: waltid/portal:${{ inputs.tag }}, waltid/portal:${{ inputs.version }}