name: iOS build and test

on:
  workflow_dispatch:
  push:

jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - name: Checkout waltid-identity
        uses: actions/checkout@v4
        with:
          repository: walt-id/waltid-identity
          path: waltid-identity
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Checkout waltid-identity-enterprise
        uses: actions/checkout@v4
        with:
          repository: walt-id/waltid-identity-enterprise
          path: waltid-identity-enterprise
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Configure gradle
        uses: ./waltid-identity/.github/actions/gradle-setup-action

      - name: Build and test iOS
        timeout-minutes: 30
        uses: ./waltid-identity/.github/actions/gradle-ios
        with:
          waltid-directory: 'waltid-identity'
