name: Run gradle build for iOS

on:
  workflow_dispatch:

jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - name: Checkout all repos with ref fallback
        uses: walt-id/waltid-identity/.github/actions/checkout-repos@d53d92cf3434925c8a2af103bf2590ddb0f7bf2f
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Configure gradle
        uses: walt-id/waltid-identity/.github/actions/gradle-setup-action@d53d92cf3434925c8a2af103bf2590ddb0f7bf2f

      - name: Build iOS Simulator Framework (ARM64)
        uses: walt-id/waltid-identity/.github/actions/gradle-ios@d53d92cf3434925c8a2af103bf2590ddb0f7bf2f
        with:
          waltid-directory: 'waltid-identity'