name: Mobile SDK API docs

on:
  workflow_dispatch:
  push:

jobs:
  dokka:
    runs-on: macos-26
    env:
      XCODE_DEVELOPER_DIR: /Applications/Xcode_26.6.app/Contents/Developer
    steps:
      - name: Checkout all repos with ref fallback
        uses: walt-id/waltid-identity/.github/actions/checkout-repos@864f84343fdeea17f6f63434bc8036c39f178dc7
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Configure gradle
        uses: walt-id/waltid-identity/.github/actions/gradle-setup-action@864f84343fdeea17f6f63434bc8036c39f178dc7

      - name: Generate mobile SDK API docs
        timeout-minutes: 30
        uses: walt-id/waltid-identity/.github/actions/gradle-mobile-sdk-docs@19f2eaf81debd0fcac891fc95bf565731bb7daf8
        with:
          waltid-directory: 'waltid-identity'
          xcode-developer-dir: ${{ env.XCODE_DEVELOPER_DIR }}
