name: Release on manual push

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      preferred: ${{ inputs.release_version }}
  gradle:
    uses: ./.github/workflows/gradle.yml
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      enable-android-build: true
      publish: true
      report-check-name: 'gradle / gradle (ubuntu-22.04)'
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      tags: '["stable", "latest"]'
      publish: true
  api-docker:
    uses: ./.github/workflows/api-docker.yml
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      tags: '["stable", "latest"]'
      publish: true
  sdk-docs:
    uses: ./.github/workflows/mobile-sdk-docs.yml
    secrets: inherit
    needs: version
    with:
      deploy: true
      version: ${{ needs.version.outputs.release_version }}
      tags: '["stable", "latest"]'
  deploy:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    needs: [ version, gradle, docker, api-docker, sdk-docs ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      deployment: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'dev' || 'prod' }}
      oss: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'test-identity-main' || 'identity-main' }}
      enterprise: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'test-enterprise-main' || 'enterprise-main' }}
  branch:
    uses: ./.github/workflows/branch.yml
    secrets: inherit
    needs: [ version, deploy ]
    if: ${{ endsWith(needs.version.outputs.release_version, '.0') && !contains(needs.version.outputs.release_version, 'PRE-RELEASE') }}
    with:
      version: ${{ needs.version.outputs.release_version }}
  enterprise-branch:
    uses: ./.github/workflows/branch.yml
    secrets: inherit
    needs: [ version, deploy ]
    if: ${{ endsWith(needs.version.outputs.release_version, '.0') && !contains(needs.version.outputs.release_version, 'PRE-RELEASE') }}
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-identity-enterprise
  docs-branch:
    uses: ./.github/workflows/branch.yml
    secrets: inherit
    needs: [ version, deploy ]
    if: ${{ endsWith(needs.version.outputs.release_version, '.0') && !contains(needs.version.outputs.release_version, 'PRE-RELEASE') }}
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-docs
  quickstart-branch:
    uses: ./.github/workflows/branch.yml
    secrets: inherit
    needs: [ version, deploy ]
    if: ${{ endsWith(needs.version.outputs.release_version, '.0') && !contains(needs.version.outputs.release_version, 'PRE-RELEASE') }}
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-enterprise-quickstart
  unified-build-branch:
    uses: ./.github/workflows/branch.yml
    secrets: inherit
    needs: [ version, deploy ]
    if: ${{ endsWith(needs.version.outputs.release_version, '.0') && !contains(needs.version.outputs.release_version, 'PRE-RELEASE') }}
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-unified-build
  tag:
    uses: ./.github/workflows/tag.yml
    secrets: inherit
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  enterprise-tag:
    uses: ./.github/workflows/tag.yml
    secrets: inherit
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-identity-enterprise
  docs-tag:
    uses: ./.github/workflows/tag.yml
    secrets: inherit
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-docs
  quickstart-tag:
    uses: ./.github/workflows/tag.yml
    secrets: inherit
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-enterprise-quickstart
  unified-build-tag:
    uses: ./.github/workflows/tag.yml
    secrets: inherit
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      repository: walt-id/waltid-unified-build
  release:
    uses: ./.github/workflows/create-release.yml
    secrets: inherit
    needs: [ version, tag ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      tag: ${{ needs.tag.outputs.tag }}
  enterprise-release:
    name: Create Enterprise Release
    runs-on: ubuntu-latest
    needs: [ enterprise-tag ]
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: walt-id/waltid-identity-enterprise
          tag_name: ${{ needs.enterprise-tag.outputs.tag }}
          prerelease: ${{ contains(needs.enterprise-tag.outputs.tag, 'PRE-RELEASE') }}
  docs-release:
    name: Create Docs Release
    runs-on: ubuntu-latest
    needs: [ docs-tag ]
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: walt-id/waltid-docs
          tag_name: ${{ needs.docs-tag.outputs.tag }}
          prerelease: ${{ contains(needs.docs-tag.outputs.tag, 'PRE-RELEASE') }}
  quickstart-release:
    name: Create Quickstart Release
    runs-on: ubuntu-latest
    needs: [ quickstart-tag ]
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: walt-id/waltid-enterprise-quickstart
          tag_name: ${{ needs.quickstart-tag.outputs.tag }}
          prerelease: ${{ contains(needs.quickstart-tag.outputs.tag, 'PRE-RELEASE') }}
  unified-build-release:
    name: Create Unified Build Release
    runs-on: ubuntu-latest
    needs: [ unified-build-tag ]
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: walt-id/waltid-unified-build
          tag_name: ${{ needs.unified-build-tag.outputs.tag }}
          prerelease: ${{ contains(needs.unified-build-tag.outputs.tag, 'PRE-RELEASE') }}
