name: Deploy manually to test environment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Custom version'
        required: false
jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/reusable/version.yml@53249535bf6e3d7257e9535ca3e9ff69472542b9
    with:
      preferred: ${{ inputs.release_version }}
  gradle:
    uses: walt-id/waltid-identity/.github/workflows/reusable/gradle.yml@53249535bf6e3d7257e9535ca3e9ff69472542b9
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/reusable/load-json.yml@53249535bf6e3d7257e9535ca3e9ff69472542b9
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/reusable/docker.yml@53249535bf6e3d7257e9535ca3e9ff69472542b9
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}s
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/reusable/deployment.yml@53249535bf6e3d7257e9535ca3e9ff69472542b9
    secrets: inherit
    needs: [ version, gradle, docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  tag:
    uses: walt-id/waltid-identity/.github/workflows/reusable/tag.yml@53249535bf6e3d7257e9535ca3e9ff69472542b9
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}