name: Deploy manually to test environment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Custom version'
        required: false
jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      preferred: ${{ inputs.release_version }}
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      tags: '["dev", "latest"]'
      publish: true
  api-docker:
    uses: ./.github/workflows/api-docker.yml
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      tags: '["dev", "latest"]'
      publish: true
  deploy:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    needs: [ version, docker, api-docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
