name: Unified release on manual push

#on:
#  workflow_dispatch:
#    inputs:
#      release_version:
#        description: 'Release version'
#        required: true
on:
  push:
    branches:
      - release-ci-cd

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@266f5c09359450c39019a6da38f2b331e7122918
    with:
      preferred: ${{ inputs.release_version }}
  gradle:
    uses: walt-id/waltid-identity/.github/workflows/gradle.yml@33b36f218fb8291fd8b434ff476f05094cb8436b
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
#      publish: true
  docker-matrix:
    uses: walt-id/waltid-identity/.github/workflows/load-json.yml@927c4233610e90dd8a57418662fad7293b7b29a4
    with:
      jsonpath: ".github/workflows/data/docker-matrix.json"
  docker:
    uses: walt-id/waltid-identity/.github/workflows/docker.yml@2d18e68bb71400e25a3ca53f8488e1197ddfdec4
    secrets: inherit
    needs: [ version, docker-matrix ]
    with:
      images: ${{ needs.docker-matrix.outputs.json }}
      version: ${{ needs.version.outputs.release_version }}
      tag: latest
#      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@33b36f218fb8291fd8b434ff476f05094cb8436b
    secrets: inherit
    needs: [ version, gradle, docker ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      deployment: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'dev' || 'prod' }}
      oss: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'test-identity-main' || 'identity-main' }}
      enterprise: ${{ contains(needs.version.outputs.release_version, 'PRE-RELEASE') && 'test-enterprise-main' || 'enterprise-main' }}
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@266f5c09359450c39019a6da38f2b331e7122918
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  release:
    uses: walt-id/waltid-identity/.github/workflows/changelog.yml@33b36f218fb8291fd8b434ff476f05094cb8436b
    secrets: inherit
    needs: [ tag ]
    with:
      tag: ${{ needs.tag.outputs.tag }}